name: namer_app
description: A new Flutter project.

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Internacionalización y UI
  easy_localization: ^3.0.0
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^4.0.4

  # Firebase (versiones compatibles entre sí)
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.4
  firebase_dynamic_links: ^5.4.8
  firebase_app_check: ^0.2.2+6

  # Herramientas y utilidades
  provider: ^6.0.0
  english_words: ^4.0.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  screenshot: ^1.3.0
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  image: ^4.0.17
  path_provider: ^2.0.11
  path: ^1.8.3
  url_launcher: ^6.1.10
  google_maps_flutter: ^2.3.0
  flutter_cache_manager: ^3.3.0
  permission_handler: ^11.2.0

  # Exportaciones
  syncfusion_flutter_xlsio: ^24.2.9
  syncfusion_flutter_pdf: ^24.1.41
  pdf: ^3.10.1
  printing: ^5.11.0
  excel: ^4.0.0
  share_plus: ^8.0.0
  month_picker_dialog: ^6.0.3
  fl_chart: ^0.70.0
  open_file_macos: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bg_pattern.png
    - assets/logo_white.png
    - assets/translations/
